version: "3.7"
services:

  pg_app:
    image: postgres
    container_name: pg_app
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: insurance_app
    restart: always
    command: ["/app_dir/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - pg_app
